package com.itcast.zjw.test

import com.itcast.zjw.drools.domain.Person;
import com.itcast.zjw.drools.domain.Classes;
import com.itcast.zjw.drools.domain.Student;
rule "ruleagenda-grop1"
	lock-on-active true
	agenda-group "001"
	when
		$student:Student(sname matches "李.*");
	then
		System.out.println($student.getSname());
		System.out.println("分组1");
end

rule "ruleagenda-grop2"
	lock-on-active true
	//agenda-group "002"
	when
		$student:Student(sname matches "李.*");
	then
		System.out.println($student.getSname());
		System.out.println("分组2");
end